#!/bin/sh
: ${SED?}

alias sed="$SED"

# Comments are allowed
res=$(printf '%s\n' 1 2 | sed 's/2/two/;#s/1/one/')
case $res in
  ('1
two') ;;
  (*) exit 9 ;;
esac

# An initial comment of #n is equivalent to -n
res=$(printf '%s\n' 1 2 | sed '#n
2p')
case $res in
  ('2') ;;
  (*) exit 8 ;;
esac
