#!/bin/sh
: ${SED?}

alias sed="$SED"

# from http://sed.sourceforge.net/grabbag/tutorials/sed1line.txt
res=$(echo foo | sed -e :a -e 's/^.\{1,7\}$/ &/;ta')
case $res in
  ('     foo') ;;
  (*) exit 9 ;;
esac
