#!/bin/sh
: ${SED?}

alias sed="$SED"

# from http://sed.sourceforge.net/grabbag/tutorials/sed1line.txt
res=$(echo foo | sed -f .fixture/-f)
case $res in
  ('     foo') ;;
  (*) exit 9 ;;
esac

# empty file
res=$(echo wrong | (sed -f .fixture/empty .fixture/right))
case $res in
  ('right') ;;
  (*) exit 8 ;;
esac
