#!/bin/sh
: ${SED?}

alias sed="$SED"

res=$(echo foo | sed 'a\
bar
')
case $res in
  ('foo
bar') ;;
  (*) exit 9 ;;
esac

res=$(echo foo | sed 'a\
bar
a\
baz
')
case $res in
  ('foo
bar
baz') ;;
  (*) exit 8 ;;
esac
