#!/bin/sh
: ${SED?}

# Single numeric address
res=$(printf 'line %s\n' 1 2 3 | $SED '2a\
bar
')
case $res in
  ('line 1
line 2
bar
line 3') ;;
  (*) exit 9 ;;
esac

# Two numeric addresses
res=$(printf 'line %s\n' 1 2 3 4 | $SED '2,3a\
bar
')
case $res in
  ('line 1
line 2
bar
line 3
bar
line 4') ;;
  (*) exit 8 ;;
esac

printf '%s passed\n' "$0"
