#!/bin/sh
: ${SED?}

alias sed="$SED"

# Change
res=$(printf '%s\n' 1 2 3 4 5 | sed '2,4c\
changed')
case $res in
  ('1
changed
5') ;;
  (*) exit 9 ;;
esac

# Interaction of 'a' and 'c'
res=$(printf '%s\n' 1 2 3 | sed '2a\
after
2c\
two
2a\
not-after')
case $res in
  ('1
two
after
3') ;;
  (*) exit 8 ;;
esac

printf '%s passed\n' "$0"
