#!/bin/sh
: ${SED?}

alias sed="$SED"

# Simple context address
res=$(printf '%s\n' 1 2 3 | sed -n '/2/p')
case $res in
  ('2') ;;
  (*) exit 9 ;;
esac

# Bug in commit 60c9c469d969886c15b2b8e38b723686681132f4
# Context Addresses should not swallow newlines.
res=$(printf '%s\n' 1 2 3 | sed -n '/1/p
/3/p')
case $res in
  ('1
3') ;;
  (*) exit 8 ;;
esac
