#!/bin/sh
: ${SED?}

alias sed="$SED"

res=$(printf '%s\n' 1 2 3 4 5 | sed '2h;4G')
case $res in
  ('1
2
3
4
2
5') ;;
  (*) exit 9 ;;
esac

# Check that initial hold space is the empty string.
res=$(printf '%s\n' 1 2 | sed '1G')
case $res in
  ('1

2') ;;
  (*) exit 8 ;;
esac

printf '%s passed\n' "$0"
