#!/bin/sh
: ${SED?}

alias sed="$SED"

# Simple case.
res=$(printf '%s\n' 1 2 3 | sed 's/2/two/')
case $res in
  ('1
two
3') ;;
  (*) exit 9 ;;
esac

# Simple BRE.
res=$(printf '%s\n' 1 2 | sed 's/$/,/')
case $res in
  ('1,
2,') ;;
  (*) exit 8 ;;
esac

# p flag.
res=$(printf '%s\n' 1 2 | sed -n 's/2/two/p')
case $res in
  ('two') ;;
  (*) exit 7 ;;
esac

printf '%s passed\n' "$0"
