#!/bin/sh
: ${SED?}

alias sed="$SED"

res=$(printf '%s\n' 1 2 3 | sed 's/2/two/')
case $res in
  ('1
two
3') ;;
  (*) exit 9 ;;
esac

res=$(printf '%s\n' 1 2 | sed 's/$/,/')
case $res in
  ('1,
2,') ;;
  (*) exit 8 ;;
esac

printf '%s passed\n' "$0"
