#!/bin/sh
: ${SED?}

alias sed="$SED"

# Test the replacement string features.

# Test & and escape forms.
res=$(printf '%s\n' 1 2 3 | sed 's/[23]/\&&\\&/')
case $res in
  ('1
&2\2
&3\3') ;;
  (*) exit 9 ;;
esac

# Test numeric backreferences.
res=$(printf '%s\n' 12 34 | sed 's/\(.\)\(.\)/\2\\\1/')
case $res in
  ('2\1
4\3') ;;
  (*) exit 8 ;;
esac

# Unmatched backreferences should be empty.
# And also, \(group\)* should match empty string.
# http://sed.sourceforge.net/sedfaq7.html#s7.13
res=$(printf '%s\n' foo | sed 's/f\(NO-MATCH\)*/g\1/')
case $res in
  ('goo') ;;
  (*) exit 7 ;;
esac
