#!/bin/sh
: ${SED?}

alias sed="$SED"

res=$(printf '%s\n' 1 2 3 | sed -n 's/2/x/
t skip
p
:skip')
case $res in
  ('1
3') ;;
  (*) exit 9 ;;
esac

# A t command should reset the flag.
res=$(printf '%s\n' 2 3 | sed -n 's/2/foo/
t skip
p
:skip
p
t skipmore
q
:skipmore')
case $res in
  ('foo') ;;
  (*) exit 8 ;;
esac

# A t with no label should branch to script end.
res=$(printf '%s\n' 1 2 3 | sed 's/2/foo/
t
s;^;+;')
case $res in
  ('+1
foo
+3') ;;
  (*) exit 7 ;;
esac
