#!/bin/sh
: ${SED?}

alias sed="$SED"

# From http://sed.sourceforge.net/grabbag/tutorials/sed1line.txt
res=$(printf '%s\n' 1 2 3 | sed '/3/{x;p;x
}')
case $res in
  ('1
2

3') ;;
  (*) exit 9 ;;
esac
