#!/bin/sh
# Add binary numbers in sed

printf '%s\n' 01011 00010 | sed -n '
s/$/,/
1{h;d}
:loop
  /1,/b dec
:shift
  /^,/b quit
  s/0,/,0/;x;s/\(.\),/,\1/;x
  b loop
:dec
  s/1,/0,/
  x
    s/1,/2,/;s/0,/1,/
  :carry
    s/02/10/
    s/12/20/
    s/^2/10/
    t carry
  x
  b shift
:quit
  x
  s/,//p
  q
'
