#!/bin/sh
# Add binary numbers in sed

printf '%s\n' ${@:-$(cat)} | sed -n '
s/$/,/
1h
1d
:loop
  /1,/b dec
:shift
  /^,/b quit
  s/0,/,0/
  x
  s/\(.\),/,\1/
  x
  b loop
:dec
  s/1,/0,/
  x
    s/1,/2,/
    s/0,/1,/
  :carry
    s/12/20/
    s/02/10/
    s/^2/10/
    t carry
  x
  b shift
:quit
  x
  s/,//p
  q
'
