#!/bin/sh

: ${SED?}

for t in test/*
do
  outcome=
  case $t in
    (test/all) ;;
    (*) printf '%s ' "$t"
      "$t" && outcome=pass
      printf '%s\n' "${outcome:-fail: exit status $?}"
      ;;
  esac
done
