#!/bin/sh

: ${SED?}

for t in test/*
do
  outcome=pass
  case $t in
    (test/all) ;;
    (*) printf '%s ' "$t"
      "$t" || outcome="fail: exit status $?"
      printf '%s\n' "$outcome"
      ;;
  esac
done
